import api from "@/config/api"
import type { SaleRequest, SaleResponse } from "@/types/Sale"

const getSalles = async (limit: number): Promise<SaleResponse[]> => {
  const { data } = await api.get("/sales", {
    params: {
      limit,
    },
  })
  const mockSales: SaleResponse[] = [
    {
      id: 1,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 201,
      clientName: "Empresa B",
      date: "2025-11-21",
      items: [
        { id: 1, name: "Mouse", price: 50 },
        { id: 2, name: "Teclado", price: 300 },
      ],
      total: 350,
    },
    {
      id: 2,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 202,
      clientName: "Empresa C",
      date: "2025-11-22",
      items: [
        { id: 3, name: "Monitor", price: 800 },
        { id: 4, name: "HD Externo", price: 400 },
        { id: 5, name: "Webcam", price: 250 },
      ],
      total: 1450,
    },
    {
      id: 3,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 203,
      clientName: "Empresa D",
      date: "2025-11-23",
      items: [{ id: 6, name: "Microfone", price: 150 }],
      total: 150,
    },
    {
      id: 4,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 204,
      clientName: "Empresa E",
      date: "2025-11-24",
      items: [
        { id: 7, name: "Impressora", price: 700 },
        { id: 8, name: "Papel A4", price: 30 },
      ],
      total: 730,
    },
    {
      id: 5,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 205,
      clientName: "Empresa F",
      date: "2025-11-25",
      items: [
        { id: 9, name: "Roteador WiFi", price: 200 },
        { id: 10, name: "Cadeira Gamer", price: 1200 },
        { id: 11, name: "Mesa Escritório", price: 800 },
      ],
      total: 2200,
    },
    {
      id: 6,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 206,
      clientName: "Empresa G",
      date: "2025-11-26",
      items: [{ id: 12, name: "Luminária LED", price: 80 }],
      total: 80,
    },
    {
      id: 7,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 207,
      clientName: "Empresa H",
      date: "2025-11-20",
      items: [
        { id: 13, name: "Suporte Monitor", price: 120 },
        { id: 14, name: "Organizador Mesa", price: 50 },
      ],
      total: 170,
    },
    {
      id: 8,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 208,
      clientName: "Empresa I",
      date: "2025-11-21",
      items: [
        { id: 15, name: "SSD 1TB", price: 600 },
        { id: 16, name: "Cabo USB-C", price: 25 },
        { id: 17, name: "Adaptador HDMI", price: 45 },
      ],
      total: 670,
    },
    {
      id: 9,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 209,
      clientName: "Empresa J",
      date: "2025-11-22",
      items: [{ id: 18, name: "Hub USB", price: 120 }],
      total: 120,
    },
    {
      id: 10,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 210,
      clientName: "Empresa K",
      date: "2025-11-23",
      items: [
        { id: 19, name: "Cooler Notebook", price: 85 },
        { id: 20, name: "Notebook", price: 2500 },
      ],
      total: 2585,
    },
    {
      id: 11,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 211,
      clientName: "Empresa L",
      date: "2025-11-24",
      items: [
        { id: 21, name: "Mouse", price: 50 },
        { id: 22, name: "Teclado", price: 300 },
        { id: 23, name: "Monitor", price: 800 },
      ],
      total: 1150,
    },
    {
      id: 12,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 212,
      clientName: "Empresa M",
      date: "2025-11-25",
      items: [{ id: 24, name: "HD Externo", price: 400 }],
      total: 400,
    },
    {
      id: 13,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 213,
      clientName: "Empresa N",
      date: "2025-11-26",
      items: [
        { id: 25, name: "Webcam", price: 250 },
        { id: 26, name: "Microfone", price: 150 },
      ],
      total: 400,
    },
    {
      id: 14,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 214,
      clientName: "Empresa O",
      date: "2025-11-20",
      items: [
        { id: 27, name: "Impressora", price: 700 },
        { id: 28, name: "Papel A4", price: 30 },
        { id: 29, name: "Roteador WiFi", price: 200 },
      ],
      total: 930,
    },
    {
      id: 15,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 215,
      clientName: "Empresa P",
      date: "2025-11-21",
      items: [{ id: 30, name: "Cadeira Gamer", price: 1200 }],
      total: 1200,
    },
    {
      id: 16,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 216,
      clientName: "Empresa Q",
      date: "2025-11-22",
      items: [
        { id: 31, name: "Mesa Escritório", price: 800 },
        { id: 32, name: "Luminária LED", price: 80 },
      ],
      total: 880,
    },
    {
      id: 17,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 217,
      clientName: "Empresa R",
      date: "2025-11-23",
      items: [
        { id: 33, name: "Suporte Monitor", price: 120 },
        { id: 34, name: "Organizador Mesa", price: 50 },
        { id: 35, name: "SSD 1TB", price: 600 },
      ],
      total: 770,
    },
    {
      id: 18,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 218,
      clientName: "Empresa S",
      date: "2025-11-24",
      items: [{ id: 36, name: "Cabo USB-C", price: 25 }],
      total: 25,
    },
    {
      id: 19,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 219,
      clientName: "Empresa T",
      date: "2025-11-25",
      items: [
        { id: 37, name: "Adaptador HDMI", price: 45 },
        { id: 38, name: "Hub USB", price: 120 },
      ],
      total: 165,
    },
    {
      id: 20,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 220,
      clientName: "Empresa U",
      date: "2025-11-26",
      items: [
        { id: 39, name: "Cooler Notebook", price: 85 },
        { id: 40, name: "Notebook", price: 2500 },
        { id: 41, name: "Mouse", price: 50 },
      ],
      total: 2635,
    },
    {
      id: 21,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 221,
      clientName: "Empresa V",
      date: "2025-11-20",
      items: [{ id: 42, name: "Teclado", price: 300 }],
      total: 300,
    },
    {
      id: 22,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 222,
      clientName: "Empresa W",
      date: "2025-11-21",
      items: [
        { id: 43, name: "Monitor", price: 800 },
        { id: 44, name: "HD Externo", price: 400 },
      ],
      total: 1200,
    },
    {
      id: 23,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 223,
      clientName: "Empresa X",
      date: "2025-11-22",
      items: [
        { id: 45, name: "Webcam", price: 250 },
        { id: 46, name: "Microfone", price: 150 },
        { id: 47, name: "Impressora", price: 700 },
      ],
      total: 1100,
    },
    {
      id: 24,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 224,
      clientName: "Empresa Y",
      date: "2025-11-23",
      items: [{ id: 48, name: "Papel A4", price: 30 }],
      total: 30,
    },
    {
      id: 25,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 225,
      clientName: "Empresa Z",
      date: "2025-11-24",
      items: [
        { id: 49, name: "Roteador WiFi", price: 200 },
        { id: 50, name: "Cadeira Gamer", price: 1200 },
      ],
      total: 1400,
    },
    {
      id: 26,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 226,
      clientName: "Empresa [",
      date: "2025-11-25",
      items: [
        { id: 51, name: "Mesa Escritório", price: 800 },
        { id: 52, name: "Luminária LED", price: 80 },
        { id: 53, name: "Suporte Monitor", price: 120 },
      ],
      total: 1000,
    },
    {
      id: 27,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 227,
      clientName: "",
      date: "2025-11-26",
      items: [{ id: 54, name: "Organizador Mesa", price: 50 }],
      total: 50,
    },
    {
      id: 28,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 228,
      clientName: "Empresa ]",
      date: "2025-11-20",
      items: [
        { id: 55, name: "SSD 1TB", price: 600 },
        { id: 56, name: "Cabo USB-C", price: 25 },
      ],
      total: 625,
    },
    {
      id: 29,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 229,
      clientName: "Empresa ^",
      date: "2025-11-21",
      items: [
        { id: 57, name: "Adaptador HDMI", price: 45 },
        { id: 58, name: "Hub USB", price: 120 },
        { id: 59, name: "Cooler Notebook", price: 85 },
      ],
      total: 250,
    },
    {
      id: 30,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 230,
      clientName: "Empresa _",
      date: "2025-11-22",
      items: [{ id: 60, name: "Notebook", price: 2500 }],
      total: 2500,
    },
    {
      id: 31,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 231,
      clientName: "Empresa `",
      date: "2025-11-23",
      items: [
        { id: 61, name: "Mouse", price: 50 },
        { id: 62, name: "Teclado", price: 300 },
      ],
      total: 350,
    },
    {
      id: 32,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 232,
      clientName: "Empresa a",
      date: "2025-11-24",
      items: [
        { id: 63, name: "Monitor", price: 800 },
        { id: 64, name: "HD Externo", price: 400 },
        { id: 65, name: "Webcam", price: 250 },
      ],
      total: 1450,
    },
    {
      id: 33,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 233,
      clientName: "Empresa b",
      date: "2025-11-25",
      items: [{ id: 66, name: "Microfone", price: 150 }],
      total: 150,
    },
    {
      id: 34,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 234,
      clientName: "Empresa c",
      date: "2025-11-26",
      items: [
        { id: 67, name: "Impressora", price: 700 },
        { id: 68, name: "Papel A4", price: 30 },
      ],
      total: 730,
    },
    {
      id: 35,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 235,
      clientName: "Empresa d",
      date: "2025-11-20",
      items: [
        { id: 69, name: "Roteador WiFi", price: 200 },
        { id: 70, name: "Cadeira Gamer", price: 1200 },
        { id: 71, name: "Mesa Escritório", price: 800 },
      ],
      total: 2200,
    },
    {
      id: 36,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 236,
      clientName: "Empresa e",
      date: "2025-11-21",
      items: [{ id: 72, name: "Luminária LED", price: 80 }],
      total: 80,
    },
    {
      id: 37,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 237,
      clientName: "Empresa f",
      date: "2025-11-22",
      items: [
        { id: 73, name: "Suporte Monitor", price: 120 },
        { id: 74, name: "Organizador Mesa", price: 50 },
      ],
      total: 170,
    },
    {
      id: 38,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 238,
      clientName: "Empresa g",
      date: "2025-11-23",
      items: [
        { id: 75, name: "SSD 1TB", price: 600 },
        { id: 76, name: "Cabo USB-C", price: 25 },
        { id: 77, name: "Adaptador HDMI", price: 45 },
      ],
      total: 670,
    },
    {
      id: 39,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 239,
      clientName: "Empresa h",
      date: "2025-11-24",
      items: [{ id: 78, name: "Hub USB", price: 120 }],
      total: 120,
    },
    {
      id: 40,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 240,
      clientName: "Empresa i",
      date: "2025-11-25",
      items: [
        { id: 79, name: "Cooler Notebook", price: 85 },
        { id: 80, name: "Notebook", price: 2500 },
      ],
      total: 2585,
    },
    {
      id: 41,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 241,
      clientName: "Empresa j",
      date: "2025-11-26",
      items: [
        { id: 81, name: "Mouse", price: 50 },
        { id: 82, name: "Teclado", price: 300 },
        { id: 83, name: "Monitor", price: 800 },
      ],
      total: 1150,
    },
    {
      id: 42,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 242,
      clientName: "Empresa k",
      date: "2025-11-20",
      items: [{ id: 84, name: "HD Externo", price: 400 }],
      total: 400,
    },
    {
      id: 43,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 243,
      clientName: "Empresa l",
      date: "2025-11-21",
      items: [
        { id: 85, name: "Webcam", price: 250 },
        { id: 86, name: "Microfone", price: 150 },
      ],
      total: 400,
    },
    {
      id: 44,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 244,
      clientName: "Empresa m",
      date: "2025-11-22",
      items: [
        { id: 87, name: "Impressora", price: 700 },
        { id: 88, name: "Papel A4", price: 30 },
        { id: 89, name: "Roteador WiFi", price: 200 },
      ],
      total: 930,
    },
    {
      id: 45,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 245,
      clientName: "Empresa n",
      date: "2025-11-23",
      items: [{ id: 90, name: "Cadeira Gamer", price: 1200 }],
      total: 1200,
    },
    {
      id: 46,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 246,
      clientName: "Empresa o",
      date: "2025-11-24",
      items: [
        { id: 91, name: "Mesa Escritório", price: 800 },
        { id: 92, name: "Luminária LED", price: 80 },
      ],
      total: 880,
    },
    {
      id: 47,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 247,
      clientName: "Empresa p",
      date: "2025-11-25",
      items: [
        { id: 93, name: "Suporte Monitor", price: 120 },
        { id: 94, name: "Organizador Mesa", price: 50 },
        { id: 95, name: "SSD 1TB", price: 600 },
      ],
      total: 770,
    },
    {
      id: 48,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 248,
      clientName: "Empresa q",
      date: "2025-11-26",
      items: [{ id: 96, name: "Cabo USB-C", price: 25 }],
      total: 25,
    },
    {
      id: 49,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 249,
      clientName: "Empresa r",
      date: "2025-11-20",
      items: [
        { id: 97, name: "Adaptador HDMI", price: 45 },
        { id: 98, name: "Hub USB", price: 120 },
      ],
      total: 165,
    },
    {
      id: 50,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 250,
      clientName: "Empresa A",
      date: "2025-11-21",
      items: [
        { id: 99, name: "Cooler Notebook", price: 85 },
        { id: 100, name: "Notebook", price: 2500 },
        { id: 101, name: "Mouse", price: 50 },
      ],
      total: 2635,
    },
    {
      id: 51,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 251,
      clientName: "Empresa B",
      date: "2025-11-22",
      items: [{ id: 102, name: "Teclado", price: 300 }],
      total: 300,
    },
    {
      id: 52,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 252,
      clientName: "Empresa C",
      date: "2025-11-23",
      items: [
        { id: 103, name: "Monitor", price: 800 },
        { id: 104, name: "HD Externo", price: 400 },
      ],
      total: 1200,
    },
    {
      id: 53,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 253,
      clientName: "Empresa D",
      date: "2025-11-24",
      items: [
        { id: 105, name: "Webcam", price: 250 },
        { id: 106, name: "Microfone", price: 150 },
        { id: 107, name: "Impressora", price: 700 },
      ],
      total: 1100,
    },
    {
      id: 54,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 254,
      clientName: "Empresa E",
      date: "2025-11-25",
      items: [{ id: 108, name: "Papel A4", price: 30 }],
      total: 30,
    },
    {
      id: 55,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 255,
      clientName: "Empresa F",
      date: "2025-11-26",
      items: [
        { id: 109, name: "Roteador WiFi", price: 200 },
        { id: 110, name: "Cadeira Gamer", price: 1200 },
      ],
      total: 1400,
    },
    {
      id: 56,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 256,
      clientName: "Empresa G",
      date: "2025-11-20",
      items: [
        { id: 111, name: "Mesa Escritório", price: 800 },
        { id: 112, name: "Luminária LED", price: 80 },
        { id: 113, name: "Suporte Monitor", price: 120 },
      ],
      total: 1000,
    },
    {
      id: 57,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 257,
      clientName: "Empresa H",
      date: "2025-11-21",
      items: [{ id: 114, name: "Organizador Mesa", price: 50 }],
      total: 50,
    },
    {
      id: 58,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 258,
      clientName: "Empresa I",
      date: "2025-11-22",
      items: [
        { id: 115, name: "SSD 1TB", price: 600 },
        { id: 116, name: "Cabo USB-C", price: 25 },
      ],
      total: 625,
    },
    {
      id: 59,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 259,
      clientName: "Empresa J",
      date: "2025-11-23",
      items: [
        { id: 117, name: "Adaptador HDMI", price: 45 },
        { id: 118, name: "Hub USB", price: 120 },
        { id: 119, name: "Cooler Notebook", price: 85 },
      ],
      total: 250,
    },
    {
      id: 60,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 260,
      clientName: "Empresa K",
      date: "2025-11-24",
      items: [{ id: 120, name: "Notebook", price: 2500 }],
      total: 2500,
    },
    {
      id: 61,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 261,
      clientName: "Empresa L",
      date: "2025-11-25",
      items: [
        { id: 121, name: "Mouse", price: 50 },
        { id: 122, name: "Teclado", price: 300 },
      ],
      total: 350,
    },
    {
      id: 62,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 262,
      clientName: "Empresa M",
      date: "2025-11-26",
      items: [
        { id: 123, name: "Monitor", price: 800 },
        { id: 124, name: "HD Externo", price: 400 },
        { id: 125, name: "Webcam", price: 250 },
      ],
      total: 1450,
    },
    {
      id: 63,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 263,
      clientName: "Empresa N",
      date: "2025-11-20",
      items: [{ id: 126, name: "Microfone", price: 150 }],
      total: 150,
    },
    {
      id: 64,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 264,
      clientName: "Empresa O",
      date: "2025-11-21",
      items: [
        { id: 127, name: "Impressora", price: 700 },
        { id: 128, name: "Papel A4", price: 30 },
      ],
      total: 730,
    },
    {
      id: 65,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 265,
      clientName: "Empresa P",
      date: "2025-11-22",
      items: [
        { id: 129, name: "Roteador WiFi", price: 200 },
        { id: 130, name: "Cadeira Gamer", price: 1200 },
        { id: 131, name: "Mesa Escritório", price: 800 },
      ],
      total: 2200,
    },
    {
      id: 66,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 266,
      clientName: "Empresa Q",
      date: "2025-11-23",
      items: [{ id: 132, name: "Luminária LED", price: 80 }],
      total: 80,
    },
    {
      id: 67,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 267,
      clientName: "Empresa R",
      date: "2025-11-24",
      items: [
        { id: 133, name: "Suporte Monitor", price: 120 },
        { id: 134, name: "Organizador Mesa", price: 50 },
      ],
      total: 170,
    },
    {
      id: 68,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 268,
      clientName: "Empresa S",
      date: "2025-11-25",
      items: [
        { id: 135, name: "SSD 1TB", price: 600 },
        { id: 136, name: "Cabo USB-C", price: 25 },
        { id: 137, name: "Adaptador HDMI", price: 45 },
      ],
      total: 670,
    },
    {
      id: 69,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 269,
      clientName: "Empresa T",
      date: "2025-11-26",
      items: [{ id: 138, name: "Hub USB", price: 120 }],
      total: 120,
    },
    {
      id: 70,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 270,
      clientName: "Empresa U",
      date: "2025-11-20",
      items: [
        { id: 139, name: "Cooler Notebook", price: 85 },
        { id: 140, name: "Notebook", price: 2500 },
      ],
      total: 2585,
    },
    {
      id: 71,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 271,
      clientName: "Empresa V",
      date: "2025-11-21",
      items: [
        { id: 141, name: "Mouse", price: 50 },
        { id: 142, name: "Teclado", price: 300 },
        { id: 143, name: "Monitor", price: 800 },
      ],
      total: 1150,
    },
    {
      id: 72,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 272,
      clientName: "Empresa W",
      date: "2025-11-22",
      items: [{ id: 144, name: "HD Externo", price: 400 }],
      total: 400,
    },
    {
      id: 73,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 273,
      clientName: "Empresa X",
      date: "2025-11-23",
      items: [
        { id: 145, name: "Webcam", price: 250 },
        { id: 146, name: "Microfone", price: 150 },
      ],
      total: 400,
    },
    {
      id: 74,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 274,
      clientName: "Empresa Y",
      date: "2025-11-24",
      items: [
        { id: 147, name: "Impressora", price: 700 },
        { id: 148, name: "Papel A4", price: 30 },
        { id: 149, name: "Roteador WiFi", price: 200 },
      ],
      total: 930,
    },
    {
      id: 75,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 275,
      clientName: "Empresa Z",
      date: "2025-11-25",
      items: [{ id: 150, name: "Cadeira Gamer", price: 1200 }],
      total: 1200,
    },
    {
      id: 76,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 276,
      clientName: "Empresa [",
      date: "2025-11-26",
      items: [
        { id: 151, name: "Mesa Escritório", price: 800 },
        { id: 152, name: "Luminária LED", price: 80 },
      ],
      total: 880,
    },
    {
      id: 77,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 277,
      clientName: "",
      date: "2025-11-20",
      items: [
        { id: 153, name: "Suporte Monitor", price: 120 },
        { id: 154, name: "Organizador Mesa", price: 50 },
        { id: 155, name: "SSD 1TB", price: 600 },
      ],
      total: 770,
    },
    {
      id: 78,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 278,
      clientName: "Empresa ]",
      date: "2025-11-21",
      items: [{ id: 156, name: "Cabo USB-C", price: 25 }],
      total: 25,
    },
    {
      id: 79,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 279,
      clientName: "Empresa ^",
      date: "2025-11-22",
      items: [
        { id: 157, name: "Adaptador HDMI", price: 45 },
        { id: 158, name: "Hub USB", price: 120 },
      ],
      total: 165,
    },
    {
      id: 80,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 280,
      clientName: "Empresa _",
      date: "2025-11-23",
      items: [
        { id: 159, name: "Cooler Notebook", price: 85 },
        { id: 160, name: "Notebook", price: 2500 },
        { id: 161, name: "Mouse", price: 50 },
      ],
      total: 2635,
    },
    {
      id: 81,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 281,
      clientName: "Empresa `",
      date: "2025-11-24",
      items: [{ id: 162, name: "Teclado", price: 300 }],
      total: 300,
    },
    {
      id: 82,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 282,
      clientName: "Empresa a",
      date: "2025-11-25",
      items: [
        { id: 163, name: "Monitor", price: 800 },
        { id: 164, name: "HD Externo", price: 400 },
      ],
      total: 1200,
    },
    {
      id: 83,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 283,
      clientName: "Empresa b",
      date: "2025-11-26",
      items: [
        { id: 165, name: "Webcam", price: 250 },
        { id: 166, name: "Microfone", price: 150 },
        { id: 167, name: "Impressora", price: 700 },
      ],
      total: 1100,
    },
    {
      id: 84,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 284,
      clientName: "Empresa c",
      date: "2025-11-20",
      items: [{ id: 168, name: "Papel A4", price: 30 }],
      total: 30,
    },
    {
      id: 85,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 285,
      clientName: "Empresa d",
      date: "2025-11-21",
      items: [
        { id: 169, name: "Roteador WiFi", price: 200 },
        { id: 170, name: "Cadeira Gamer", price: 1200 },
      ],
      total: 1400,
    },
    {
      id: 86,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 286,
      clientName: "Empresa e",
      date: "2025-11-22",
      items: [
        { id: 171, name: "Mesa Escritório", price: 800 },
        { id: 172, name: "Luminária LED", price: 80 },
        { id: 173, name: "Suporte Monitor", price: 120 },
      ],
      total: 1000,
    },
    {
      id: 87,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 287,
      clientName: "Empresa f",
      date: "2025-11-23",
      items: [{ id: 174, name: "Organizador Mesa", price: 50 }],
      total: 50,
    },
    {
      id: 88,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 288,
      clientName: "Empresa g",
      date: "2025-11-24",
      items: [
        { id: 175, name: "SSD 1TB", price: 600 },
        { id: 176, name: "Cabo USB-C", price: 25 },
      ],
      total: 625,
    },
    {
      id: 89,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 289,
      clientName: "Empresa h",
      date: "2025-11-25",
      items: [
        { id: 177, name: "Adaptador HDMI", price: 45 },
        { id: 178, name: "Hub USB", price: 120 },
        { id: 179, name: "Cooler Notebook", price: 85 },
      ],
      total: 250,
    },
    {
      id: 90,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 290,
      clientName: "Empresa i",
      date: "2025-11-26",
      items: [{ id: 180, name: "Notebook", price: 2500 }],
      total: 2500,
    },
    {
      id: 91,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 291,
      clientName: "Empresa j",
      date: "2025-11-20",
      items: [
        { id: 181, name: "Mouse", price: 50 },
        { id: 182, name: "Teclado", price: 300 },
      ],
      total: 350,
    },
    {
      id: 92,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 292,
      clientName: "Empresa k",
      date: "2025-11-21",
      items: [
        { id: 183, name: "Monitor", price: 800 },
        { id: 184, name: "HD Externo", price: 400 },
        { id: 185, name: "Webcam", price: 250 },
      ],
      total: 1450,
    },
    {
      id: 93,
      sellerId: 106,
      sellerName: "Lucia Ferreira",
      clientId: 293,
      clientName: "Empresa l",
      date: "2025-11-22",
      items: [{ id: 186, name: "Microfone", price: 150 }],
      total: 150,
    },
    {
      id: 94,
      sellerId: 107,
      sellerName: "Bruno Alves",
      clientId: 294,
      clientName: "Empresa m",
      date: "2025-11-23",
      items: [
        { id: 187, name: "Impressora", price: 700 },
        { id: 188, name: "Papel A4", price: 30 },
      ],
      total: 730,
    },
    {
      id: 95,
      sellerId: 108,
      sellerName: "Camila Rocha",
      clientId: 295,
      clientName: "Empresa n",
      date: "2025-11-24",
      items: [
        { id: 189, name: "Roteador WiFi", price: 200 },
        { id: 190, name: "Cadeira Gamer", price: 1200 },
        { id: 191, name: "Mesa Escritório", price: 800 },
      ],
      total: 2200,
    },
    {
      id: 96,
      sellerId: 101,
      sellerName: "João Silva",
      clientId: 296,
      clientName: "Empresa o",
      date: "2025-11-25",
      items: [{ id: 192, name: "Luminária LED", price: 80 }],
      total: 80,
    },
    {
      id: 97,
      sellerId: 102,
      sellerName: "Maria Santos",
      clientId: 297,
      clientName: "Empresa p",
      date: "2025-11-26",
      items: [
        { id: 193, name: "Suporte Monitor", price: 120 },
        { id: 194, name: "Organizador Mesa", price: 50 },
      ],
      total: 170,
    },
    {
      id: 98,
      sellerId: 103,
      sellerName: "Pedro Costa",
      clientId: 298,
      clientName: "Empresa q",
      date: "2025-11-20",
      items: [
        { id: 195, name: "SSD 1TB", price: 600 },
        { id: 196, name: "Cabo USB-C", price: 25 },
        { id: 197, name: "Adaptador HDMI", price: 45 },
      ],
      total: 670,
    },
    {
      id: 99,
      sellerId: 104,
      sellerName: "Ana Oliveira",
      clientId: 299,
      clientName: "Empresa r",
      date: "2025-11-21",
      items: [{ id: 198, name: "Hub USB", price: 120 }],
      total: 120,
    },
    {
      id: 100,
      sellerId: 105,
      sellerName: "Carlos Mendes",
      clientId: 300,
      clientName: "Empresa A",
      date: "2025-11-22",
      items: [
        { id: 199, name: "Cooler Notebook", price: 85 },
        { id: 200, name: "Notebook", price: 2500 },
      ],
      total: 2585,
    },
  ]
  return data
}

const createSale = async (sale: SaleRequest) => {
  const { data } = await api.post("/sales/create", sale)
  return data
}

const updateSale = async (id: number, sale: SaleRequest) => {
  const { data } = await api.put(`/sales/${id}`, sale)
  return data
}

const deleteSale = async (id: number) => {
  const { data } = await api.delete(`/sales/${id}`)
  return data
}

export default {
  getSalles,
  createSale,
  updateSale,
  deleteSale,
}
